from __future__ import annotations

import importlib.util
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = ROOT / "tools" / "build_research_dashboard.py"
SPEC = importlib.util.spec_from_file_location("build_research_dashboard", MODULE_PATH)
assert SPEC and SPEC.loader
dashboard = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(dashboard)


class ResearchDashboardTest(unittest.TestCase):
    def test_payload_uses_current_reviewed_evidence(self) -> None:
        payload = dashboard.build_payload()

        self.assertEqual(payload["snapshot"]["task"], "PRT-002-A1")
        self.assertEqual(payload["snapshot"]["phase"], "P2 / PDD 因果诊断")
        self.assertEqual(payload["snapshot"]["status"], "MEASURED / REVIEW_PASSED")
        self.assertEqual(payload["snapshot"]["taskStatus"], "APPROVED_WITH_CONDITIONS / AUDIT_FIRST")
        self.assertTrue(payload["snapshot"]["reviewedCommit"].startswith("01ec41b"))
        self.assertEqual(len(payload["runs"]), 4)
        metrics = {item["field"]: item for item in payload["metrics"]}
        self.assertTrue(metrics["APvt_official_1500"]["pass"])
        self.assertEqual(round(metrics["APvt_official_1500"]["mean"], 4), 0.0103)
        self.assertTrue(metrics["ARvt_2_8_3000"]["pass"])
        self.assertEqual(round(metrics["ARvt_2_8_3000"]["mean"], 4), 0.0131)

    def test_payload_surfaces_governance_and_document_drift(self) -> None:
        payload = dashboard.build_payload()
        titles = {item["title"] for item in payload["blockers"]}

        self.assertNotIn("EVIDENCE_LEDGER.md 尚未同步当前审查", titles)
        self.assertIn("research_brief_v0.1.md 尚未同步当前审查", titles)
        self.assertNotIn("A1 实验报告尚待机械修正", titles)
        self.assertTrue(any("WP0–WP2" in action["action"] for action in payload["nextActions"]))
        self.assertEqual(payload["phases"][2]["status"], "AUDIT_AUTHORIZED")

    def test_rendered_data_contains_stable_fingerprint(self) -> None:
        payload = dashboard.build_payload()
        rendered = dashboard.render_js(payload)

        self.assertTrue(rendered.startswith("// Generated by tools/build_research_dashboard.py"))
        self.assertIsNotNone(re.search(r'"sourceFingerprint": "[0-9a-f]{64}"', rendered))
        self.assertIn("window.RESEARCH_DASHBOARD_DATA", rendered)


if __name__ == "__main__":
    unittest.main()
