// Generated by tools/build_research_dashboard.py; do not edit by hand.
window.RESEARCH_DASHBOARD_DATA = {
  "schemaVersion": 1,
  "generatedAt": "2026-08-26T17:57:46+08:00",
  "snapshot": {
    "date": "2026-08-26",
    "status": "MEASURED / REVIEW_PASSED",
    "phase": "P2 / PDD 受控诊断设计",
    "task": "PRT-002-A1",
    "taskStatus": "DESIGN_PENDING / EXECUTION_LOCKED",
    "reviewedCommit": "01ec41b0f052a170116185b2cd481c36ae3d725a",
    "role": "研究设计 agent",
    "scope": "独立 2–8 px 极小目标检测副线",
    "permission": "允许设计 PRT-002-A1；新任务卡与设计审查批准前正式运行锁定。"
  },
  "git": {
    "branch": "codex/research-evidence-audit",
    "head": "347d493878eccf85ffb0328c88492e953187cb15",
    "dirty": true,
    "dirtyEntries": [
      "?? outputs/PRT-001/tests/"
    ],
    "remoteExperiment": "01ec41b0f052a170116185b2cd481c36ae3d725a",
    "remoteMain": "c7fa77ba9837ceeb148c94750579341fdc72c893",
    "integratedIntoMain": false
  },
  "phases": [
    {
      "id": "P0",
      "name": "问题与评测协议冻结",
      "status": "DONE",
      "evidence": "2–8 px 问题、AI-TOD-v2、双口径 evaluator 与 CCF-C 节奏已版本化。"
    },
    {
      "id": "P1",
      "name": "P2 基线证据补全",
      "status": "DONE",
      "evidence": "两 seed 核心 Gate 与报告一致性条件均已通过。"
    },
    {
      "id": "P2",
      "name": "PDD 受控诊断与改版",
      "status": "DESIGN_PENDING",
      "evidence": "A1 已通过，允许建立 PRT-002-A1 任务卡；正式执行仍锁定。"
    },
    {
      "id": "P3",
      "name": "SSR 条件增益验证",
      "status": "LOCKED",
      "evidence": "必须等待 PDD 阶段决策，不允许提前堆叠模块。"
    },
    {
      "id": "P4",
      "name": "泛化、效率与论文证据",
      "status": "LOCKED",
      "evidence": "跨检测器/数据集、尺寸分桶和真实延迟均未测试。"
    }
  ],
  "metrics": [
    {
      "field": "APvt_official_1500",
      "label": "官方 APvt",
      "seed0": 0.009499999999999998,
      "seed1": 0.0111,
      "mean": 0.0103,
      "threshold": 0.005,
      "pass": true
    },
    {
      "field": "ARvt_2_8_3000",
      "label": "项目 ARvt [2,8)",
      "seed0": 0.013500000000000002,
      "seed1": 0.0126,
      "mean": 0.01305,
      "threshold": 0.01,
      "pass": true
    },
    {
      "field": "AP",
      "label": "总体 AP",
      "seed0": 0.0312,
      "seed1": 0.0282,
      "mean": 0.029699999999999997,
      "threshold": -0.002,
      "pass": true
    }
  ],
  "runs": [
    {
      "model": "B0",
      "seed": 0,
      "AP": 0.017,
      "AP50": 0.0542,
      "AP75": 0.0064,
      "APvt_official_1500": 0.0041,
      "ARvt_official_1500": 0.0034,
      "ARvt_2_8_3000": 0.0029,
      "AP_2_8_3000": 0.0037,
      "APt_official_1500": "0.0199",
      "APs_official_1500": "0.0193",
      "AR_1500": "0.0711",
      "checkpoint_sha256": "aa818352075aca11bd8ace446091fd78c274e1c4cc12fabb0e7e529178a3a036",
      "prediction_json_sha256": "9f6d949df389a6c7cdcb00bbb77044264d0aaae7b6bce8900cfcd97e4dce39a2"
    },
    {
      "model": "B0",
      "seed": 1,
      "AP": 0.0103,
      "AP50": 0.0366,
      "AP75": 0.0033,
      "APvt_official_1500": 0.0007,
      "ARvt_official_1500": 0.0003,
      "ARvt_2_8_3000": 0.0002,
      "AP_2_8_3000": 0.0005,
      "APt_official_1500": "0.0128",
      "APs_official_1500": "0.0101",
      "AR_1500": "0.0372",
      "checkpoint_sha256": "a834f800e0c2f8a9c76ef2e709ef3ea8f7eb45ea216e558b8871922357bfb28f",
      "prediction_json_sha256": "5bd80ce11e38508c738166c824549eebdc4bbf02ced4de07bf49c28286a5b8d3"
    },
    {
      "model": "B1",
      "seed": 0,
      "AP": 0.0482,
      "AP50": 0.121,
      "AP75": 0.0301,
      "APvt_official_1500": 0.0136,
      "ARvt_official_1500": 0.0175,
      "ARvt_2_8_3000": 0.0164,
      "AP_2_8_3000": 0.0127,
      "APt_official_1500": "0.0545",
      "APs_official_1500": "0.0713",
      "AR_1500": "0.1039",
      "checkpoint_sha256": "a189d7b76676ce6601c7c37c639f700120cb4fed0fd4b0d7b25bb1fe2beb9076",
      "prediction_json_sha256": "62d616954d72cf5854e6962545a6bdbbb50654f7ae26bae76076e8fbd53e5566"
    },
    {
      "model": "B1",
      "seed": 1,
      "AP": 0.0385,
      "AP50": 0.1036,
      "AP75": 0.0209,
      "APvt_official_1500": 0.0118,
      "ARvt_official_1500": 0.0137,
      "ARvt_2_8_3000": 0.0128,
      "AP_2_8_3000": 0.0103,
      "APt_official_1500": "0.0447",
      "APs_official_1500": "0.0494",
      "AR_1500": "0.0988",
      "checkpoint_sha256": "2721e64a371d80eb52ba7406e8b320e7c1498cdddad0ee893ba2b762c3d2463b",
      "prediction_json_sha256": "7b608a19d4dee0c45c0306e75eae2fe305c8f740ef79e40f1d4575c079f99837"
    }
  ],
  "evidence": [
    {
      "claim": "P2–P6 改善极小目标基线",
      "status": "ACCEPTED",
      "basis": "AI-TOD-v2，FCOS-R50，12 epochs，seeds 0/1"
    },
    {
      "claim": "P2 收益在两个 seed 方向一致",
      "status": "MEASURED",
      "basis": "APvt、精确 ARvt、总体 AP 均为正"
    },
    {
      "claim": "PDD 有效",
      "status": "NOT_ESTABLISHED",
      "basis": "PDD v1 零 AP；根因解释未验证"
    },
    {
      "claim": "SSR / PRTiny 有效",
      "status": "NOT_TESTED",
      "basis": "正式任务仍锁定"
    },
    {
      "claim": "跨数据集 / 检测器泛化",
      "status": "NOT_TESTED",
      "basis": "尚无受审原始证据"
    },
    {
      "claim": "真实加速或效率收益",
      "status": "NOT_TESTED",
      "basis": "无同 GPU latency/FPS 协议测量"
    }
  ],
  "blockers": [
    {
      "severity": "GOVERNANCE",
      "title": "研究治理状态尚未进入 main",
      "detail": "当前研究 HEAD 不是 origin/main 的祖先；后续阶段启动前需完成审阅集成。",
      "owner": "用户 / 研究设计 agent"
    },
    {
      "severity": "DRIFT",
      "title": "research_brief_v0.1.md 尚未同步当前审查",
      "detail": "文件最新日期 UNKNOWN，当前状态快照为 2026-08-26。",
      "owner": "研究设计 agent"
    }
  ],
  "nextActions": [
    {
      "order": 1,
      "owner": "用户 / 研究设计 agent",
      "action": "审阅并将已通过的 A1 治理状态集成到 main。"
    },
    {
      "order": 2,
      "owner": "研究设计 agent",
      "action": "建立 PRT-002-A1 小预算受控诊断任务卡。"
    },
    {
      "order": 3,
      "owner": "研究设计 agent",
      "action": "完成 PRT-002-A1 设计审查并冻结科学变量。"
    },
    {
      "order": 4,
      "owner": "实验执行 agent",
      "action": "获批后从最新 main 建立独立实验分支并执行。"
    }
  ],
  "records": {
    "reviews": [
      {
        "path": "research/reviews/2026-08-26-PRT-001-A1-result-review-3.md",
        "title": "实验结果审查：PRT-001-A1（Result Review 3 / Final）",
        "status": "REVIEW_PASSED"
      },
      {
        "path": "research/reviews/2026-08-26-PRT-001-A1-result-review-2.md",
        "title": "实验结果审查：PRT-001-A1（Result Review 2）",
        "status": "REVIEW_PASSED_WITH_CONDITIONS"
      },
      {
        "path": "research/reviews/2026-08-26-PRT-001-A1-result-review-1.md",
        "title": "实验结果审查：PRT-001-A1（Result Review 1）",
        "status": "REVISION_REQUIRED"
      },
      {
        "path": "research/reviews/2026-08-23-PRT-002-result-review-2.md",
        "title": "实验结果审查：PRT-002（PDD v1 证据与归因复核）",
        "status": "REVISION_REQUIRED"
      },
      {
        "path": "research/reviews/2026-08-23-PRT-001-result-review-final.md",
        "title": "里程碑结果审查记录：PRT-001 (基线终审报告)",
        "status": "RECORDED"
      },
      {
        "path": "research/reviews/2026-08-23-PRT-001-result-review-2.md",
        "title": "实验结果审查：PRT-001（证据充分性复核）",
        "status": "REVISION_REQUIRED"
      },
      {
        "path": "research/reviews/2026-08-23-PRT-001-A1-design-review-2.md",
        "title": "实验设计审查：PRT-001-A1（Review 2）",
        "status": "APPROVED_WITH_CONDITIONS"
      },
      {
        "path": "research/reviews/2026-08-23-PRT-001-A1-design-review-1.md",
        "title": "实验设计审查：PRT-001-A1",
        "status": "APPROVED_WITH_CONDITIONS"
      }
    ],
    "tasks": [
      {
        "path": "experiment_handoffs/tasks/PRT-002-pdd-module-and-ablation.md",
        "title": "阶段实验任务卡：PRT-002 (PDD 局部细节保留下采样模块设计与受控验证)",
        "status": "APPROVED"
      },
      {
        "path": "experiment_handoffs/tasks/PRT-001-baseline-and-tiny-evaluator.md",
        "title": "PRT-001：AI-TOD-v2 可重复基线与极小目标评估器验证",
        "status": "RECORDED"
      },
      {
        "path": "experiment_handoffs/tasks/PRT-001-amendment-1-evidence-completion.md",
        "title": "阶段实验任务卡：PRT-001-A1（极小目标基线证据补全与可复现确认）",
        "status": "APPROVED_WITH_CONDITIONS"
      }
    ]
  },
  "sources": [
    {
      "path": "AGENTS.md",
      "role": "项目总约束"
    },
    {
      "path": "docs/memory/CURRENT_STATE.md",
      "role": "当前状态快照"
    },
    {
      "path": "research/reviews/2026-08-26-PRT-001-A1-result-review-3.md",
      "role": "当前正式结果审查"
    },
    {
      "path": "experiment_handoffs/tasks/PRT-001-amendment-1-evidence-completion.md",
      "role": "当前任务卡 v1.1"
    },
    {
      "path": "outputs/PRT-001-A1/summary.csv",
      "role": "四组受审轻量指标（读取自 origin/codex/exp-prt-001-a1）"
    },
    {
      "path": "experiment_handoffs/results/PRT-001-A1-evidence-completion.md",
      "role": "实验自查报告（读取自 origin/codex/exp-prt-001-a1）"
    }
  ],
  "reviewExcerpt": "[REVIEW_PASSED][PRT-001-A1] 里程碑审查通过，可以进入 PRT-002-A1 设计阶段；正式实验须等待新任务卡和设计审查批准。",
  "updateCommand": "python tools/build_research_dashboard.py --fetch",
  "sourceFingerprint": "cfed5bfe9414decbc510423c07a9c1c176eef7ea2fa5c350b84b58c78dff336b"
};
